import { randomUUID } from "node:crypto";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArtifactContent } from "@/components/artifacts/artifact-content";
import { CheckIcon, ClockIcon, LockIcon, ShieldIcon, SparkIcon } from "@/components/icons";
import { ParentShell } from "@/components/shells/parent-shell";
import { StatusBadge } from "@/components/ui/status-badge";
import { getParentAccessState } from "@/lib/auth/parent";
import { validationReportSchema, type ArtifactKind } from "@/lib/generation/contracts";
import { getArtifactReview } from "@/lib/generation/repository";
import { getArtifactPublicationState } from "@/lib/publication/repository";
import { ACTIVE_RECOVERY, recoveryLockMessage } from "@/lib/recovery/status";
import { approveArtifact, rejectArtifact, requestGeneration } from "../../generation/actions";
import { archiveArtifact, archiveLearningWeek, archiveLessonAssignment, createLearningWeek, publishLessonAssignment, replaceLessonAssignment, revokeArtifactApproval, scheduleLessonAssignment, setLessonAssignmentReplay, withdrawLessonAssignment } from "../../publication/actions";
import styles from "../../parent.module.css";

export const metadata: Metadata = { title: "Artifact Review | Alonso Academy" };

const labels: Record<string, string> = { weekly_plan: "Weekly plan", daily_lesson: "Daily lesson", review_lesson: "Review lesson", story_lesson: "Listening story", parent_summary: "Parent summary" };

const activeAssignmentStatuses = new Set(["assigned", "scheduled", "published"]);
const terminalAssignmentStatuses = new Set(["withdrawn", "replaced", "completed"]);
const publicationMessages: Record<string, string> = {
  "week-created": "The five-day learning week was created. Every day now has an authoritative slot.",
  scheduled: "This exact lesson version is scheduled, but it is not visible to Alonso yet.",
  published: "This exact lesson version is now the one published mission visible to Alonso.",
  replaced: "The previous assignment was replaced with the selected approved lesson version.",
  withdrawn: "The assignment was withdrawn and is no longer visible to Alonso.",
  "assignment-archived": "The terminal assignment record was archived.",
  "approval-revoked": "Approval was revoked. This artifact is private and cannot be assigned.",
  "artifact-archived": "The private artifact version was archived.",
  "week-archived": "The learning week was archived.",
  "replay-enabled": "Replay is enabled after Alonso completes this assignment.",
  "replay-disabled": "Replay is disabled for this assignment.",
};

function localDateTimeValue(date = new Date()) {
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
}

export default async function ArtifactReviewPage({ params, searchParams }: { params: Promise<{ artifactId: string }>; searchParams: Promise<{ generated?: string; reused?: string; approved?: string; rejected?: string; error?: string; publication?: string; publicationError?: string }> }) {
  const access = await getParentAccessState();
  if (access.status !== "ready") redirect("/login");
  const [{ artifactId }, query] = await Promise.all([params, searchParams]);
  const [data, publication] = await Promise.all([getArtifactReview(artifactId).catch(() => notFound()), getArtifactPublicationState(artifactId)]);
  const report = validationReportSchema.safeParse(data.artifact.validation_report).success ? validationReportSchema.parse(data.artifact.validation_report) : null;
  const canApprove = !ACTIVE_RECOVERY.productMutationsLocked && data.artifact.status === "validated";
  const canReject = !ACTIVE_RECOVERY.productMutationsLocked && ["draft", "validation_failed", "validated"].includes(data.artifact.status);
  const canRegenerate = !ACTIVE_RECOVERY.productMutationsLocked && !ACTIVE_RECOVERY.generationLocked && data.artifact.kind !== "parent_summary";
  const isLesson = ["daily_lesson", "review_lesson", "story_lesson"].includes(data.artifact.kind);
  const activeAssignment = publication.available ? publication.activeSlotAssignment : null;
  const artifactActiveAssignment = activeAssignment?.lesson_artifact_id === data.artifact.id ? activeAssignment : null;
  const artifactHasActiveAssignment = publication.available && publication.artifactAssignments.some((assignment) => activeAssignmentStatuses.has(assignment.status));
  const terminalAssignment = publication.available ? publication.artifactAssignments.find((assignment) => terminalAssignmentStatuses.has(assignment.status)) ?? null : null;
  const replayAssignment = publication.available ? publication.artifactAssignments.find((assignment) => ["assigned", "scheduled", "published", "completed"].includes(assignment.status)) ?? null : null;
  const publicationChainReady = publication.available && publication.curriculumApproved && publication.weeklyPlan?.status === "approved" && Boolean(publication.learningWeek && ["planned", "active"].includes(publication.learningWeek.status));
  const assignmentWindowOpen = !artifactActiveAssignment?.available_until || new Date(artifactActiveAssignment.available_until).getTime() > Date.now();
  const canSchedule = Boolean(publication.available && publicationChainReady && isLesson && data.artifact.status === "approved" && data.artifact.binding_status === "valid" && data.artifact.runtime_ready && publication.slot && !activeAssignment);
  const canPublish = Boolean(artifactActiveAssignment && publicationChainReady && assignmentWindowOpen && data.artifact.status === "approved" && data.artifact.binding_status === "valid" && data.artifact.runtime_ready && ["assigned", "scheduled"].includes(artifactActiveAssignment.status));
  const canWithdraw = Boolean(artifactActiveAssignment && activeAssignmentStatuses.has(artifactActiveAssignment.status));
  const canReplace = Boolean(artifactActiveAssignment && publicationChainReady);
  const canRevokeApproval = publication.available && data.artifact.status === "approved" && !artifactHasActiveAssignment
    && !(data.artifact.kind === "weekly_plan" && publication.learningWeek?.status !== "archived")
    && !publication.artifactAssignments.some((assignment) => assignment.status === "completed" && assignment.replay_allowed);
  const canArchiveArtifact = publication.available && ["draft", "validation_failed", "validated"].includes(data.artifact.status);
  const weekHasActiveAssignment = publication.available && publication.assignments.some((assignment) => activeAssignmentStatuses.has(assignment.status));
  const canCreateWeek = Boolean(publication.available && publication.curriculumApproved && data.artifact.kind === "weekly_plan" && data.artifact.status === "approved" && !publication.learningWeek && publication.child);
  const canArchiveWeek = Boolean(publication.available && data.artifact.kind === "weekly_plan" && publication.learningWeek && ["planned", "active", "completed"].includes(publication.learningWeek.status) && !weekHasActiveAssignment);

  return <ParentShell identity={access.email}><main className={styles.dashboard} id="main-content">
    <header className={styles.reviewHeader}><div><Link className={styles.textLink} href="/parent/generation">← Generation studio</Link><p className={styles.eyebrow}>{labels[data.artifact.kind]} · Version {data.artifact.version}</p><h1>Review every detail.</h1><p>Validation can enforce boundaries. Only you can decide whether this version is right for Alonso.</p></div><StatusBadge status={data.artifact.status === "approved" ? "ready" : data.artifact.status === "validated" ? "waiting" : "locked"}>{data.artifact.status.replaceAll("_", " ")}</StatusBadge></header>

    {query.generated && <p className={styles.notice}>A new immutable version was generated and validated. {query.reused ? "This was the existing result for the repeated request." : "It remains private until you approve it."}</p>}
    {query.approved && <p className={styles.notice}>This exact version is approved. The decision is recorded in the audit history.</p>}
    {query.rejected && <p className={styles.notice}>This version was archived with your rejection note. You may regenerate a new version.</p>}
    {query.error && <p className={styles.error}>The decision was not recorded. The version may have changed state, the note may be too short, or its curriculum snapshot may be stale.</p>}
    {query.publication && publicationMessages[query.publication] && <p className={styles.notice}>{publicationMessages[query.publication]}</p>}
    {query.publicationError && <p className={styles.error}>The publication change was not recorded. Check the current state and prerequisites below; the database kept the previous authoritative record unchanged.</p>}
    {ACTIVE_RECOVERY.productMutationsLocked && <p className={styles.notice}>{recoveryLockMessage()} Existing content and decision history remain read-only.</p>}

    <section className={styles.reviewLayout}><article className={styles.contentReview}><ArtifactContent kind={data.artifact.kind} content={data.artifact.content} /></article><aside className={styles.validationRail}><div className={styles.railHeading}><span className={styles.cardIcon}>{report?.valid ? <CheckIcon size={21} /> : <ClockIcon size={21} />}</span><p className={styles.cardLabel}>Validation report</p><h2>{report?.valid ? "All boundaries passed" : "Review required"}</h2></div><dl><div><dt>Schema and targets</dt><dd>{report?.deterministicValid ? "Passed" : "Failed"}</dd></div><div><dt>Semantic review</dt><dd>{report?.semanticValid === true ? "Passed" : report?.semanticValid === false ? "Failed" : "Not run"}</dd></div><div><dt>Model</dt><dd>{data.artifact.model_id ?? "Not recorded"}</dd></div><div><dt>Snapshot</dt><dd>{typeof data.artifact.curriculum_snapshot === "object" && data.artifact.curriculum_snapshot && !Array.isArray(data.artifact.curriculum_snapshot) && typeof data.artifact.curriculum_snapshot.snapshotId === "string" ? data.artifact.curriculum_snapshot.snapshotId.slice(0, 10) : "Unavailable"}</dd></div></dl>{report?.issues.length ? <div className={styles.issueList}><h3>Reported issues</h3>{report.issues.map((issue, index) => <article key={`${issue.code}-${index}`}><strong>{issue.code.replaceAll("_", " ")}</strong><p>{issue.message}</p><small>{issue.path}</small></article>)}</div> : <p className={styles.railSuccess}><ShieldIcon size={18} /> No validation violations recorded.</p>}</aside></section>

    {data.children.length > 0 && <section className={styles.childVersions}><p className={styles.cardLabel}>Lessons created from this week</p><div>{data.children.map((child) => <Link href={`/parent/artifacts/${child.id}`} key={child.id}><span>Day {child.day_number}</span><strong>{labels[child.kind]} · v{child.version}</strong><small>{child.status.replaceAll("_", " ")}</small></Link>)}</div></section>}

    <section className={styles.decisionSection} aria-labelledby="publication-controls-title">
      <div><p className={styles.eyebrow}>Publication boundary</p><h2 id="publication-controls-title">Approval never makes a lesson visible.</h2><p>Scheduling, publishing, replacing, withdrawing, revoking approval, and archiving are separate recorded parent decisions. Each action below is shown only when the current authoritative state allows it.</p></div>
      {!publication.available ? <div className={styles.approvedPlate}><LockIcon size={24} /><strong>Publication unavailable</strong><span>{publication.reason}</span></div> : <div className={styles.decisionForms}>
        {data.artifact.kind === "weekly_plan" && publication.learningWeek && <div className={styles.decisionForm}><p className={styles.cardLabel}>Five exact day slots</p><strong>{publication.learningWeek.status} week</strong>{[1, 2, 3, 4, 5].map((day) => {
          const slot = publication.slots.find((candidate) => candidate.day_number === day);
          const assignment = slot ? publication.assignments.find((candidate) => candidate.week_day_slot_id === slot.id && activeAssignmentStatuses.has(candidate.status)) : null;
          return <p key={day}>Day {day}: {slot ? `${slot.title} — ${assignment?.status ?? "no active assignment"}` : "slot missing — publication blocked"}</p>;
        })}</div>}

        {canCreateWeek && <form action={createLearningWeek} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="childId" value={publication.child?.id ?? ""} /><input type="hidden" name="timezone" value="America/New_York" /><label htmlFor="week-start">Optional week start</label><input id="week-start" name="startsOn" type="date" /><label htmlFor="week-note">Creation note</label><textarea id="week-note" name="note" minLength={5} required placeholder="Why should this approved plan become Alonso's five-day week?" /><button type="submit"><CheckIcon size={18} />Create five-day learning week</button></form>}
        {data.artifact.kind === "weekly_plan" && data.artifact.status === "approved" && !publication.learningWeek && !publication.curriculumApproved && <div className={styles.decisionForm}><strong>Week creation blocked</strong><p>The curriculum unit must be approved before this plan can become a learning week.</p></div>}
        {data.artifact.kind === "weekly_plan" && data.artifact.status === "approved" && !publication.learningWeek && !publication.child && <div className={styles.decisionForm}><strong>Week creation blocked</strong><p>A child profile must exist before this approved plan can create five day slots.</p></div>}
        {data.artifact.kind === "weekly_plan" && data.artifact.status !== "approved" && !publication.learningWeek && <div className={styles.decisionForm}><strong>Week creation prerequisite</strong><p>Approve this plan privately first. Approval records your decision but does not publish any lesson.</p></div>}

        {isLesson && <div className={styles.decisionForm}><p className={styles.cardLabel}>Exact lesson state</p><strong>{publication.slot ? `Day ${publication.slot.day_number}: ${publication.slot.title}` : "No authoritative day slot"}</strong><p>Artifact: {data.artifact.status.replaceAll("_", " ")} · Binding: {data.artifact.binding_status.replaceAll("_", " ")} · Runtime: {data.artifact.runtime_ready ? "ready" : "not ready"}</p><p>Assignment: {artifactActiveAssignment?.status ?? (activeAssignment ? `slot occupied by another version (${activeAssignment.status})` : "none")}</p></div>}
        {canSchedule && <form action={scheduleLessonAssignment} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="slotId" value={publication.slot?.id ?? ""} /><label htmlFor="available-from">Available from</label><input id="available-from" name="availableFrom" type="datetime-local" defaultValue={localDateTimeValue()} required /><label htmlFor="available-until">Available until (optional)</label><input id="available-until" name="availableUntil" type="datetime-local" /><label htmlFor="schedule-note">Scheduling note</label><textarea id="schedule-note" name="note" minLength={5} required placeholder="Why should this version be scheduled for Alonso?" /><button type="submit"><ClockIcon size={18} />Schedule exact version</button></form>}
        {canPublish && <form action={publishLessonAssignment} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="assignmentId" value={artifactActiveAssignment?.id ?? ""} /><label htmlFor="publish-note">Publication note</label><textarea id="publish-note" name="note" minLength={5} required placeholder="Why should this scheduled version become Alonso's visible mission?" /><button type="submit"><CheckIcon size={18} />Publish to Alonso</button></form>}
        {artifactActiveAssignment && ["assigned", "scheduled"].includes(artifactActiveAssignment.status) && !canPublish && <div className={styles.decisionForm}><strong>Publication prerequisite</strong><p>{!publication.curriculumApproved ? "The curriculum unit is not approved." : publication.weeklyPlan?.status !== "approved" ? "The weekly plan approval is not active." : !publication.learningWeek || !["planned", "active"].includes(publication.learningWeek.status) ? "The learning week is not planned or active." : !assignmentWindowOpen ? "This assignment's availability window has ended." : data.artifact.status !== "approved" ? "This exact lesson version is no longer approved." : data.artifact.binding_status !== "valid" || !data.artifact.runtime_ready ? "The lesson binding or runtime contract is no longer valid." : "The current record cannot be published."}</p></div>}
        {canWithdraw && <form action={withdrawLessonAssignment} className={`${styles.decisionForm} ${styles.rejectForm}`}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="assignmentId" value={artifactActiveAssignment?.id ?? ""} /><label htmlFor="withdraw-reason">Withdrawal reason</label><textarea id="withdraw-reason" name="reason" minLength={5} required placeholder="Why should this assignment stop being available?" /><button type="submit">Withdraw assignment</button></form>}
        {canReplace && publication.replacementCandidates.length > 0 && <form action={replaceLessonAssignment} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="assignmentId" value={artifactActiveAssignment?.id ?? ""} /><label htmlFor="replacement-artifact">Approved replacement</label><select id="replacement-artifact" name="replacementArtifactId" required>{publication.replacementCandidates.map((candidate) => <option value={candidate.id} key={candidate.id}>{labels[candidate.kind]} · version {candidate.version}</option>)}</select><label htmlFor="activation-mode">Replacement state</label><select id="activation-mode" name="activationMode" defaultValue="assigned"><option value="assigned">Assigned privately</option><option value="scheduled">Scheduled privately</option><option value="published">Publish immediately</option></select><label htmlFor="replacement-from">Available from (required when scheduled)</label><input id="replacement-from" name="availableFrom" type="datetime-local" /><label htmlFor="replacement-until">Available until (optional)</label><input id="replacement-until" name="availableUntil" type="datetime-local" /><label htmlFor="replacement-note">Replacement note</label><textarea id="replacement-note" name="note" minLength={5} required placeholder="Why is the selected version the correct replacement?" /><button type="submit">Replace exact assignment</button></form>}
        {canReplace && publication.replacementCandidates.length === 0 && <div className={styles.decisionForm}><strong>No valid replacement exists</strong><p>Create, validate, and privately approve another runtime-ready version bound to this exact day slot before replacing.</p></div>}
        {artifactActiveAssignment && !canReplace && <div className={styles.decisionForm}><strong>Replacement prerequisite</strong><p>The curriculum unit, weekly plan, and learning week must all be in an approved active state before another version can replace this assignment.</p></div>}
        {terminalAssignment && <form action={archiveLessonAssignment} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="assignmentId" value={terminalAssignment.id} /><label htmlFor="assignment-archive-reason">Assignment archive reason</label><textarea id="assignment-archive-reason" name="reason" minLength={5} required placeholder="Why should this terminal assignment leave the active history view?" /><button type="submit">Archive assignment record</button></form>}
        {replayAssignment && <form action={setLessonAssignmentReplay} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="assignmentId" value={replayAssignment.id} /><input type="hidden" name="replayAllowed" value={replayAssignment.replay_allowed ? "false" : "true"} /><label htmlFor="replay-note">Replay decision note</label><textarea id="replay-note" name="note" minLength={5} required placeholder="Why should replay be enabled or disabled for this assignment?" /><button type="submit">{replayAssignment.replay_allowed ? "Disable replay" : "Enable replay after completion"}</button></form>}

        {isLesson && !canSchedule && !artifactActiveAssignment && <div className={styles.decisionForm}><strong>Scheduling prerequisite</strong><p>{data.artifact.status !== "approved" ? "Approve this artifact privately first." : !publication.slot ? "This artifact is not bound to an authoritative day slot." : !publication.curriculumApproved ? "The curriculum unit is not approved." : publication.weeklyPlan?.status !== "approved" ? "The weekly plan approval is not active." : !publication.learningWeek || !["planned", "active"].includes(publication.learningWeek.status) ? "The learning week must be planned or active." : data.artifact.binding_status !== "valid" ? "The artifact-to-slot binding must validate successfully." : !data.artifact.runtime_ready ? "The lesson runtime contract must be ready before assignment." : activeAssignment ? "This day slot already has an active assignment. Open that assigned version to replace or withdraw it." : "The current record does not satisfy the scheduling contract."}</p></div>}

        {canRevokeApproval && <form action={revokeArtifactApproval} className={`${styles.decisionForm} ${styles.rejectForm}`}><input type="hidden" name="artifactId" value={data.artifact.id} /><label htmlFor="revocation-reason">Approval revocation reason</label><textarea id="revocation-reason" name="reason" minLength={5} required placeholder="Why should this private approval be removed?" /><button type="submit">Revoke approval</button></form>}
        {canArchiveArtifact && <form action={archiveArtifact} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><label htmlFor="artifact-archive-reason">Artifact archive reason</label><textarea id="artifact-archive-reason" name="reason" minLength={5} required placeholder="Why should this private artifact version be archived?" /><button type="submit">Archive artifact version</button></form>}
        {canArchiveWeek && <form action={archiveLearningWeek} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><input type="hidden" name="learningWeekId" value={publication.learningWeek?.id ?? ""} /><label htmlFor="week-archive-reason">Week archive reason</label><textarea id="week-archive-reason" name="reason" minLength={5} required placeholder="Why should this week be archived?" /><button type="submit">Archive learning week</button></form>}
        {publication.learningWeek && weekHasActiveAssignment && data.artifact.kind === "weekly_plan" && <div className={styles.decisionForm}><strong>Week archival blocked</strong><p>Withdraw, replace, or complete every active assignment in this week before archiving it.</p></div>}
      </div>}
    </section>

    <section className={styles.decisionSection} aria-labelledby="decision-title"><div><p className={styles.eyebrow}>Decision history</p><h2 id="decision-title">{ACTIVE_RECOVERY.productMutationsLocked ? `Read-only during ${ACTIVE_RECOVERY.phase}` : data.artifact.status === "approved" ? "Approved privately" : "What should happen to this version?"}</h2><p>Every recorded decision applies only to version {data.artifact.version}. Approval never creates an assignment and never makes a lesson visible to Alonso.</p></div>{ACTIVE_RECOVERY.productMutationsLocked ? <div className={styles.approvedPlate}><ShieldIcon size={24} /><strong>Decisions paused</strong><span>{data.artifact.status.replaceAll("_", " ")} record</span></div> : data.artifact.status === "approved" ? <div className={styles.approvedPlate}><CheckIcon size={24} /><strong>Approved privately</strong><span>{data.approvals[0]?.note ?? "Decision recorded; no child visibility was granted."}</span></div> : <div className={styles.decisionForms}>{canApprove && <form action={approveArtifact} className={styles.decisionForm}><input type="hidden" name="artifactId" value={data.artifact.id} /><label htmlFor="approval-note">Private approval note</label><textarea id="approval-note" name="note" minLength={5} required placeholder="Why is this version appropriate for Alonso?" /><button type="submit"><CheckIcon size={18} />Approve privately</button></form>}{canReject && <form action={rejectArtifact} className={`${styles.decisionForm} ${styles.rejectForm}`}><input type="hidden" name="artifactId" value={data.artifact.id} /><label htmlFor="rejection-note">Rejection note</label><textarea id="rejection-note" name="note" minLength={5} required placeholder="What should change in the next version?" /><button type="submit">Reject and archive</button></form>}{canRegenerate && <form action={requestGeneration} className={`${styles.decisionForm} ${styles.regenerateForm}`}><input type="hidden" name="kind" value={data.artifact.kind as ArtifactKind} /><input type="hidden" name="unitId" value={data.artifact.curriculum_unit_id} /><input type="hidden" name="day" value={data.artifact.day_number ?? ""} /><input type="hidden" name="previousArtifactId" value={data.artifact.id} /><input type="hidden" name="idempotencyKey" value={randomUUID()} /><label htmlFor="regeneration-request">Direction for a new version</label><textarea id="regeneration-request" name="parentRequest" minLength={8} required placeholder="Describe the precise change you want while preserving the curriculum boundary." /><button type="submit"><SparkIcon size={18} />Regenerate as version {data.artifact.version + 1}</button></form>}</div>}</section>
  </main></ParentShell>;
}
