export const recovery2Characters = [
  {
    id: "miko",
    name: "Miko",
    role: "Guide and sound scout",
    color: "teal",
    job: "Greets Alonso, models first, makes listening visible, and owns calm recovery.",
  },
  {
    id: "pippa",
    name: "Pippa",
    role: "Action and gesture guide",
    color: "coral",
    job: "Turns verbs and routines into clear whole-body demonstrations.",
  },
  {
    id: "moss",
    name: "Moss",
    role: "Meaning and object guide",
    color: "moss",
    job: "Builds concrete object scenes and keeps picture choices honest.",
  },
  {
    id: "nia",
    name: "Nia",
    role: "Conversation and story partner",
    color: "gold",
    job: "Creates a real reason to greet, answer, take a turn, and retell.",
  },
] as const;

export const recovery2Arc = [
  { step: "Arrive", minutes: "0:45", owner: "Miko", purpose: "Greeting and one visible purpose" },
  { step: "Model", minutes: "1:15", owner: "Miko", purpose: "Hear and watch the complete meaning" },
  { step: "Understand", minutes: "2:00", owner: "Moss", purpose: "Connect speech to image or action" },
  { step: "Imitate", minutes: "1:30", owner: "Miko", purpose: "Low-pressure echo with gesture" },
  { step: "Discriminate", minutes: "2:00", owner: "Moss", purpose: "Listen and find among fair choices" },
  { step: "Reset", minutes: "1:00", owner: "Pippa", purpose: "Move, regulate, and rehearse meaning" },
  { step: "Use", minutes: "2:30", owner: "Nia", purpose: "Take a meaningful spoken turn" },
  { step: "Retrieve", minutes: "1:30", owner: "Pippa", purpose: "Recall after movement and delay" },
  { step: "Exit", minutes: "1:30", owner: "Miko", purpose: "Independent listening or spoken evidence" },
  { step: "Complete", minutes: "0:45", owner: "Miko", purpose: "Reflect honestly and preview the path" },
] as const;

export const recovery2Interactions = [
  {
    id: "home",
    number: "01",
    title: "Alonso Home",
    place: "Welcome Dock",
    spokenLine: "Hello, Alonso. Your mission is ready.",
    childAction: "Tap one large mission marker.",
    fallback: "Miko repeats, waves, and points to the same marker.",
    evidence: "No learning score. Entry and required first listen only.",
    artClass: "world",
  },
  {
    id: "listen-find",
    number: "02",
    title: "Listen and find",
    place: "Word Gallery",
    spokenLine: "Listen. Touch the apple.",
    childAction: "Choose one large picture from three fair options.",
    fallback: "Replay, then Miko demonstrates listening; reduce choices only after a prompt is recorded.",
    evidence: "Server keeps first choice, replay count, prompt level, and response time.",
    artClass: "listen",
  },
  {
    id: "conversation",
    number: "03",
    title: "Character conversation",
    place: "Welcome Dock",
    spokenLine: "Hello! My name is Nia. Say, ‘Hello.’",
    childAction: "Take one short spoken turn after Nia becomes still.",
    fallback: "A greeting gesture and semantic picture response preserve the same meaning.",
    evidence: "Spoken attempt stays distinct from modeled or picture-supported success.",
    artClass: "conversation",
  },
  {
    id: "speaking",
    number: "04",
    title: "Speaking and recording",
    place: "Sound Workshop",
    spokenLine: "Your turn. Say, ‘Hello.’",
    childAction: "Press once to start a short, bounded recording.",
    fallback: "Silence, denial, or provider failure returns to the same turn with one obvious choice.",
    evidence: "No raw audio; retain only derived outcome, timing, confidence, and support.",
    artClass: "speaking",
  },
  {
    id: "story",
    number: "05",
    title: "Story and retell",
    place: "Story Camp",
    spokenLine: "First, Miko leaves. Next, he finds the ball. What happens last?",
    childAction: "Choose or say the final story beat.",
    fallback: "Nia acts the three beats and keeps every picture visible as a memory anchor.",
    evidence: "Sequence choice and supported retell are stored as different evidence types.",
    artClass: "story",
  },
  {
    id: "completion",
    number: "06",
    title: "Completion",
    place: "Current location",
    spokenLine: "Your mission is complete. Let's remember what you did.",
    childAction: "Return to the dock with one clear action.",
    fallback: "Replay is secondary and appears only when the parent allowed it.",
    evidence: "Reflects only the response modes actually recorded, without grades, stars, streaks, or mastery claims.",
    artClass: "completion",
  },
  {
    id: "collection",
    number: "07",
    title: "Learned-word collection",
    place: "Word Gallery",
    spokenLine: "Find the apple you know.",
    childAction: "Tap a familiar picture to hear and see its meaning again.",
    fallback: "Moss groups moments by place and action, never by locked rarity.",
    evidence: "Retrieval can create new evidence; browsing alone never changes mastery.",
    artClass: "collection",
  },
] as const;

export const recovery2ConceptAssets = [
  {
    reviewKey: "luma.cast.anchor.v1",
    label: "Cast anchor",
    kind: "character",
    state: "in_review",
    permittedUse: "Cast identity and art-direction review only",
    path: "/recovery-2/concepts/luma-cast-concept-v1.png",
    sha256: "897225eac720347ad874f4ad5bf70db751998c062b2c70b13fc26f108043fd66",
    alt: "Miko, Pippa, Moss, and Nia standing together on warm paper.",
  },
  {
    reviewKey: "luma.world.home.v1",
    label: "Luma Landing world",
    kind: "scene",
    state: "in_review",
    permittedUse: "World and composition review only",
    path: "/recovery-2/concepts/luma-landing-world-v1.png",
    sha256: "b40bb9a7f2862f4200b3c08d45dd9f2c322b24af340ce1190ee86d5ee5b85d13",
    alt: "Luma Landing islands connected by paths with five teaching locations and the four guides.",
  },
  {
    reviewKey: "luma.miko.teaching-poses.v1",
    label: "Miko teaching poses",
    kind: "character_pose",
    state: "in_review",
    permittedUse: "Teaching-pose direction review only",
    path: "/recovery-2/concepts/miko-teaching-poses-v1.png",
    sha256: "c6c95760dd54e3a180ec078c2576853a638d80974aaab17bd7ba9ade182abd4a",
    alt: "Six Miko poses for greeting, listening, speaking, pointing, helping, and celebrating effort.",
  },
  {
    reviewKey: "luma.interactions.storyboard.v1",
    label: "Interaction story art",
    kind: "ui_illustration",
    state: "in_review",
    permittedUse: "Directional storyboard; the apple-pointing frame is non-scored demonstration only",
    path: "/recovery-2/concepts/luma-interactions-v1.png",
    sha256: "bccfd44c214db14f7cde72b2b816b2606273f27ec8d95d3660e73377cf7c785a",
    alt: "Four scenes showing listen and find, character greeting, story retell, and learned-word collection.",
  },
] as const;

export const recovery2ApprovalItems = [
  "Character cast: Miko, Pippa, Moss, and Nia",
  "World and child art direction: Luma Landing",
  "Seven child interaction and audio concepts",
  "Adult parent-workspace direction",
  "Generated concept assets: each exact registered version",
] as const;
